### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by aniketp** [yashsriv/resume#1]
Compilation with xelatex : `xelatex resume.tex` removes the header content
[resume.pdf](https://github.com/yashsriv/resume/files/981350/resume.pdf)

It does not show any error btw.
@yashsriv

**Comment by yashsriv** [comment]
Doesn't on my pc 😄 . What is your version of `xelatex`? Mine is `3.14159265-2.6-0.99996`... also a system library is required for this. I can't remember which one. Something related to graphics.

This should give you a correct output:
```
xelatex "\def\cvprint{1} \input{resume.tex}"
```

**Comment by aniketp** [comment]
Thanks @yashsriv . It worked :smile:
